### ISSUE TITLE
Images are not clear

### ISSUE THREAD

**Issue by Cheffrey2000** [learn-co-curriculum/dsc-git-collab-recap#2]
## Link to Canvas

https://learning.flatironschool.com/courses/153/pages/bash-and-git-recap?module_item_id=28275

## Issue Subtype

- [ ] Master branch code
- [ ] Solution branch code
- [ ] Code tests
- [ x] Layout/rendering issue
- [ ] Instructions unclear
- [ ] Other (explain below)

## Describe the Issue
Images are unclear and text in them is very small
### Source

```

```

### Concern

It is difficult to see the text in the images which makes them not useful.

## What OS Are You Using?

- [ x] OS X
- [ ] Windows
- [ ] WSL
- [ ] Linux
- [ ] IllumiDesk

**Comment by jessepisel** [comment]
fixed with #3. Closing at this time
